### ISSUE TITLE
Enhancement: Request for metadata extraction code to be available via a function

### ISSUE THREAD

**Issue by RubenGarcia** [alican/django-tus#10]
### Description
The following code from views.py is useful on its own; it would be good to have it in its own exported function.

    upload_metadata = request.META.get("HTTP_UPLOAD_METADATA", None)
    metadata = {}
    if upload_metadata:
            for kv in upload_metadata.split(","):
                (key, value) = kv.split(" ")
                metadata[key] = base64.b64decode(value).decode("utf-8")

**Comment by alican** [comment]
I'm working right now on the code and I already excludet lots of things to own method. I will push in the hours my actual state to the 3.x branch.

**Comment by alican** [comment]
implemented with recent updates
