### ISSUE TITLE
500 error on patch request

### ISSUE THREAD

**Issue by RubenGarcia** [alican/django-tus#16]
* django-tus version: master / 4cc2ecc816be0bd89048c58bc4f9002f3f6c9efa
* Django version: 3.1.2
* Python version: 3.6.9
* Operating System: Ubuntu 18.04.5

### Description
The following request
```
curl -i -H "Authorization: Bearer $1" \
    -H "tus-resumable: 1.0.0" \
    -H "upload-offset: 0" \
    -H "content-type: application/offset+octet-stream " \
    --data-binary "@file" \
	-X PATCH \
	https://<host>/upload/2ecff761-5da5-4f34-86a8-efa7ea8a2b49
```
produces
```
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
which eventually ends up as a 500 Internal Server Error instead of 204 or 404. I don't think there is an issue with the request itself, but if there is, I think you should return 400 Bad Request here.

The line producing the error is tusfile.py line 60
```
self.file_size = int(cache.get("tus-uploads/{}/file_size".format(resource_id)))
```
### What I Did

```
curl -i -H "Authorization: Bearer $1" \
    -H "tus-resumable: 1.0.0" \
    -H "upload-offset: 0" \
    -H "content-type: application/offset+octet-stream " \
    --data-binary "@file" \
	-X PATCH \
	https://<host>/upload/2ecff761-5da5-4f34-86a8-efa7ea8a2b49
```
produced
```
HTTP/1.1 100 Continue^M
^M
HTTP/1.1 500 Internal Server Error^M 
...
```

**Comment by alican** [comment]
@RubenGarcia Hey, can you check if the bug is fixed? I think you get the error because their was no check if the resource_id exists. Now I added a check and it will raise an 404 error if its not found.

**Comment by RubenGarcia** [comment]
I will check it after the holidays, but in principle that looks like a good solution.
