### ISSUE TITLE
Problem with uploading second file

### ISSUE THREAD

**Issue by aminkashiri** [alican/django-tus#17]
* django-tus version: 0.5.0
* Django version:3.1.2
* Python version: 3.8.5
* Operating System: Ubuntu 18.04 LTS

### Description
Hi. I cloned the example project given: 
https://github.com/alican/django-tus-example/

Everything was working file, until in tried to upload another file! The first file uploaded successfully, and i was able to pause/resume with no problem. But after that, when i try to upload another file (a different file), it gives me the error:

> Failed because: Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: http://127.0.0.1:8000/upload/561811a-f40d-49cc-a11e-0e7e224f5b9, response code: 410, response text: , request id: n/a)
Do you want to retry?

And the Django output looked like this:

> Unable to create file: [Errno 2] No such file or directory: '/home/amin/Workspaces/PythonWorkspace/Django/django-tus-example/tus_upload/3a17d19b-4915-427c-a5cd-18965a93358c'
Traceback (most recent call last):
  File "/home/amin/anaconda3/envs/csv_support/lib/python3.8/site-packages/django_tus/tusfile.py", line 136, in write_init_file
    self._write_file(self.get_path(), self.file_size, b"\0")
  File "/home/amin/anaconda3/envs/csv_support/lib/python3.8/site-packages/django_tus/tusfile.py", line 122, in _write_file
    with open(path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/amin/Workspaces/PythonWorkspace/Django/django-tus-example/tus_upload/3a17d19b-4915-427c-a5cd-18965a93358c'
[16/Oct/2020 07:46:13] "POST /upload/ HTTP/1.1" 201 0
Gone: /upload/3a17d19b-4915-427c-a5cd-18965a93358c
[16/Oct/2020 07:46:13] "PATCH /upload/3a17d19b-4915-427c-a5cd-18965a93358c HTTP/1.1" 410 0

### What I Did

And then, i started examining the code. The problem was that when tus wanted to write to the second file, the '/tus_upload/' directory was not there (it is deleted, because in the last line of TusFile.rename function, you use os.renames() , and os.renames deletes parent empty folders when changing a files name). So the problem is: the tus_upload directory is deleted and is never recreated, until I restart the Django server. I mean, whenever I start Django again, this directory is created again, but after the first upload, the directory is being deleted.

So, to solve the problem, i changed the line:
`os.renames(self.get_path(), os.path.join(settings.TUS_DESTINATION_DIR, self.filename)) `
to:
`os.rename(self.get_path(), os.path.join(settings.TUS_DESTINATION_DIR, self.filename))`
(just removing the 's' in os.renames()). And that worked! (because os.rename() doesn't delete parent empty folders by default)

I hope i cleared things up and it could help.

**Comment by alican** [comment]
Hey, thank you for your issue, good explanation and solution. I will fix it in the repository
