### ISSUE TITLE
Chunking uploads are writing null bytes to the start of the file.

### ISSUE THREAD

**Issue by jsproull** [alican/django-tus#18]
* django-tus version: 0.5.0
* Django version: 3.1.2
* Python version: 3.8.6
* Operating System: OSX 10.14.6

### Description

Using django-tus-example (as well as my project)
Uploading a 16mb .zip file (I have tried many different files), the .zip file ends up containing only the last chunk. The start of the file up to the last offset is filled with null bytes. If I change `tusfile.py`'s `_write_file()` to use "wa" instead of "wb" and append without `seek`ing it works fine.

### What I Did

I have tried this on Ubuntu as well as OSX and have tried Python 3.5/3.6 and 3.9. Is anyone else seeing this? I feel like I'm going crazy. :)

**Comment by RubenGarcia** [comment]
You want 'ab': append, and binary mode. 'b' may be the default on OSX but it is needed on other platforms. "wa" does not seem to be a valid mode (https://docs.python.org/2/library/functions.html#open)

**Comment by jsproull** [comment]
wa works, but only if writing sequentially (which is not guaranteed from a tus client)

`'a' for appending (which on some Unix systems means that all writes append to the end of the file regardless of the current seek position)`

I'm still confused as to why `wb+` isn't working. Can anyone else reproduce this? I've reproduced it on 3 versions of OSX and 2 versions of Ubuntu.

**Comment by arturzx** [comment]
Same problem to me when using ngx-uploadx and tus-js-client. File begins with zeroes and only last chunk is written properly.

**Comment by arturzx** [comment]
I've made test:
```
name = 'test'
a = [b'\xAA', b'\xBB', b'\xCC', b'\xDD', b'\xEE', b'\xFF']

with open(name, 'wb') as f:
    f.seek(len(a))
    f.write(b'\0')

for off, x in enumerate(a):
    with open(name, 'wb') as f:
        f.seek(off)
        f.write(x)

with open(name, 'rb') as f:
    print(f.read())
```

and result:
```
b'\x00\x00\x00\x00\x00\xff'
```
From doc:
```
'r' | open for reading (default)
'w' | open for writing, truncating the file first
'x' | open for exclusive creation, failing if the file already exists
'a' | open for writing, appending to the end of the file if it exists
'b' | binary mode
't' | text mode (default)
'+' | open for updating (reading and writing)
```
So, when using 'wb' in _write_file(), file is truncated every time. We need 'r+b' mode.
