### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by guettli** [alican/django-tus#8]
Hi,

there is no update since more than two years.

What is the state of the project?

It is 100% ok if you have no time for it.

But maybe you have a good hint which tool could be used to get "interruptible uploads in django"?

**Comment by RubenGarcia** [comment]
I would also be interested in knowing if this is still being maintained, and what versions of django are supported.

**Comment by RubenGarcia** [comment]
It seems django1 would work, but django2 and django3 give: ImportError: No module named 'django.core.urlresolvers'

**Comment by mbaechtold** [comment]
@guettli, I'm not the maintainer of this package but I'm keen to learn what you want to know exactly when you are talking about the "state" of the package? 

This package seems to be working for the Djangos mentioned in the [setup.py](https://github.com/alican/django-tus/blob/d69af0699f5e4bb66d11eda32a8704ee171a7e52/setup.py#L54-L55).

Are you missing certain features? Is something broken? Do you need the package to support other releases of Django?

**Comment by alican** [comment]
Hello, I'm the maintainer of this project. Sorry For my long absence. I will update the project in the next days, fix some bugs, make it compatible with the newest django version and put some test for future development.

**Comment by RubenGarcia** [comment]
Thanks!

**Comment by RubenGarcia** [comment]
I think this issue can now be closed.
